---
  - name: Install Apache.
    hosts: all
    become: true

    vars:
      apache_package: apache2
      apache_service: apache2
      apache_conf_dir: /etc/
  
    handlers:
      - import_tasks: handlers/apache.yml

    tasks:
      - import_tasks: tasks/apache.yml
  - import_playbook: app.yml