---
- name: wordpress
  hosts: all
  become: true

  vars_files:
    - "vars/main.yml"
  tasks:
    - debug: var=hostvars[inventory_hostname]['inventory_hostname']

  roles:
    - { role: docker, tags: ['docker'] }
    - { role: network, tags: ['network'] }
    - { role: wordpress, tags: ['wordpress', 'allcontainers'] }
    - { role: mysql, tags: ['mysql', 'allcontainers'] }
    - { role: webserver, tags: ['webserver', 'allcontainers'] }   
    - { role: phpmyadmin, tags: ['phpmyadmin', 'allcontainers'] }