---
- name: Install Apache
      apt: name=apache2 state=present update_cache=true

- name: Configure Apache
  template: src=apache2.conf dest=/etc/apache2/apache2.conf owner=root group=root mode=0644
  notify: Restart apache