---
- name: creat wordpress directory
  command: mkdir -p wordpress/conf

- name: copy dockerfile
  copy:
    src: ./resources/wordpress/Dockerfile
    dest: ./wordpress/

- name: copy wpconf.sh config
  copy:
    src: ./resources/wordpress/conf/wpconf.sh
    dest: ./wordpress/conf

- name: copy wp-config
  copy:
    src: ./resources/wordpress/conf/wp-config.php
    dest: ./wordpress/conf


- name: build wordpress image
  shell: |
    while [ ! -f ./wordpress/Dockerfile ]; do sleep 5; done && 
      docker build -t wordpress ./wordpress

- name: docker run wordpress
  docker_container:
    name: wordpress
    image: wordpress
    state: started
    ports: 
      - 9000:9000
    expose:
      - 9000