---
- name: Ensure Apache is installed.
  apt: 
    name: "{{ apache_package }}"
    state: present

- name: Copy the Apache config file.
  copy:
    src: test
    dest: "{{ apache_conf_dir }}/test.conf"
  notify: restart apache

- name: Ensure Apache is running and starts at boot.
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
