---
- name: generate ssl cert and key
  shell: openssl req -x509 -nodes -days 365 \
    -subj "/C=KH/ST=KH/O=Company, Inc./CN=myamani.42.fr" \
    -addext "subjectAltName=DNS:myamani.42.fr" \
    -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt;