---
  - name: Install Apache.
    hosts: all
    become: true

    vars:
      apache_package: apache2
      apache_service: apache2
      apache_conf_dir: /etc/apache2/sites-enabled

    handlers:
      - name: restart apache
        service: name="{{ apache_service }}" state=restarted
      - name: just a test
        debug: msg="{{ apache_package }}"

    tasks:
      - name: Ensure Apache is installed.
        apt: 
          name: "{{ apache_package }}"
          state: present
        notify: just a test
      
      - name: Copy the Apache config file.
        copy:
          src: test
          dest: "{{ apache_conf_dir }}/test.conf"
        notify: restart apache

      - name: Ensure Apache is running and starts at boot.
        service:
          name: "{{ apache_service }}"
          state: started
          enabled: yes
          