---
- name: cache update
  apt:
    update_cache: yes

- name: Install curl and python3-pip
  apt:
    name:
      - curl
      - python3-pip
      - openssl
    state: present

- name: install docker sdk for python
  pip:
    name: docker
    
- name: curl get-docker.sh script
  shell: curl -sSL https://get.docker.com/ | sh

- name: start docker
  service:
    name: docker
    state: started

- name: enable docker
  service:
    name: docker
    enabled: yes

- name: get docker compose
  command: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: make docker compose executable
  command: chmod +x /usr/local/bin/docker-compose