---
- name: Install Apache
  hosts: all
  
  tasks:
    - name: Install Apache
      command: apt-get install -quiet -y httpd httpd-devel
    - name: Copy configuration files.
      command: >
        
