---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - unzip
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - docker-compose
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: 
      - docker
      - docker-compose

# - vars:
#     container_count: 4
#     default_container_name: docker
#     default_container_image: ubuntu
#     default_container_command: sleep 1d

# - name: Pull default Docker image
#   community.docker.docker_image:
#     name: "{{ default_container_image }}"
#     source: pull

# - name: Create default containers
#   community.docker.docker_container:
#     name: "{{ default_container_name }}{{ item }}"
#     image: "{{ default_container_image }}"
#     command: "{{ default_container_command }}"
#     state: present
#   with_sequence: count={{ container_count }}



  # - name: docker
  #   apt:
  #     name:
  #       - apt-transport-https
  #       - ca-certificates
  #       - curl
  #       - gnupg-agent
  #       - software-properties-common
  #     update_cache: yes

  # - name: add apt-key
  #   apt_key:
  #     url: https://download.docker.com/linux/ubuntu/gpg

  # - name: add docker repo
  #   command: apt-key add -

  # - name: add repo
  #   apt_repository:
  #     repo: deb [arch=amd64] https://download.docker.com/ubuntu focal stable

  # - name: install docker
  #   apt:
  #     name:
  #       - docker-ce
  #       - docker-ce-cli
  #       - containerd.io
  #     update_cache: yes

  # - name: add userpermissions
  #   shell: "usermod -aG docker {{ lookup('env','USER') }}"

  # - name: install python package manager
  #   apt:
  #     name: python3-pip

  # - name: install python sdk
  #   become_user: "{{ lookup('env','USER') }}"
  #   pip:
  #     name:
  #       - docker
  #       - docker-compose

...